name: Dismiss code reviews from collaborators

on:
  workflow_call:
  

jobs:
  approver-vibe-check:
    name: Dismiss code reviews from collaborators
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dismiss code reviews from collaborators
        run: 'dist/index.js'
      
      
